name: Auto Deploy on linux server

on:
  push:
    branches:
      - main
      - staging-branch

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check github.ref
        run: echo "The full ref is ${{ github.ref }}"

      - name: Deploy Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/konvertHRNode
            git pull origin main
            npm install
            pm2 reload ecosystem.config.js --only konverthr-API

  deploy-staging:
    if: github.ref == 'refs/heads/staging-branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check github.ref
        run: echo "The full ref is ${{ github.ref }}"

      - name: Deploy Staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/staging.konverthr.com
            git pull origin staging-branch
            npm install
            pm2 reload ecosystem.config.js --only konverthr-staging
